### ISSUE TITLE
Would you recommend setting VLCtube to "execute last" ?

### ISSUE THREAD

**Issue by LL25255252** [jackun/VLCTube#64]
If so, maybe I suggest you to recommend it at the script's homepage.

I have re-enabled  "View Youtube videos by same user" script" (a new fixed 1.9 version was uploaded a few days ago after some weeks it was broken).
https://greasyfork.org/en/scripts/946-view-youtube-videos-by-same-user
I don't have exact STR (Searched for a video on youtube.com and on the results page I reloaded the page and then clicked on one of the results to watch it) but when VLCtube run before that VYVBSU script I had some problems (like that my stylish css style didn't launch).

The STR should be not so different from the ones you gave me on issue #33.

After I entered the addons manager and set VLCtube to "execute last" the problems dissappeared.

BTW - can "execute last" solve also issue #41 ? (both are related to youtube's SPF)

"View Youtube videos by same user" version 1.9
VLCtube 61.7
Firefox 38.0.1
Win 7 x64

TIA.

**Comment by jackun** [comment]
Had a quick look, current VYVBSU shouldn't interfere with VLCTube so execution order shouldn't matter much though.

I have to check if some CSS isn't reinjected from somewhere accidentally then as Stylish probably can't deal with SPF. Can you add the CSS class names or element IDs that get "undone"?

# 41 still happens when SPF is enabled too? I think only the plugin is kept resident but main VLC executable gets reloaded on every load. File system caching etc should still keep it fairly fast though.
Can check with Resource Monitor if it is loading VLC otherwise it might be that Firefox hangs on too heavy/aggressive DOM manipulation by the script (though with SPF it should be quite minimal).

**Comment by LL25255252** [comment]
regarding #41 - I have no idea if it's still happening - I just saw that the issue is still "open" and it's relating to SPF...

And yes I was wrong. Execution order is not the problem.

Still,  I have now the exact STR:
1. open a new/fresh Firefox profile.
2. Install Stylish * Greasemonkey.
3. Install VLCtube 61.7
4. install this very small userstyle - https://userstyles.org/styles/53623/youtube-bigger-font-for-description-and-comments
5. search something with the youtube searchbar 
6. On youtube's results page click the reload button.
7. Click to watch on one of the results.
8. The userstyle you installed is not loaded. (you need to reload to launch it)

**Comment by jackun** [comment]
Hmm, mostly works for me. The description's font sometimes lags and changes when the comments get loaded (my laptop showing its age probably). But you can probably set the style to be included everywhere on "youtube.com" not just just "/watch"  (@-moz-document domain(...) maybe).

**Comment by LL25255252** [comment]
It turns out that as you said before the problem is that Stylish doesn't deal well with SPF. I've even reproduced the problem after disabling Greasemonkey.
Your workaround also worked. In my userstyle above I changed url-prefix(https://www.youtube.com/watch) to domain(youtube.com) and the problem is gone.
Thanks a lot for all your help :)
You can now change the title of this thread if you want and close it.
